import {
  Activity,
  AppWindow,
  Archive,
  BarChart,
  Bell,
  Bot,
  Box,
  Boxes,
  Cloud,
  Code,
  Cog,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Database,
  FileText,
  Flame,
  Folder,
  Gamepad2,
  Globe,
  HardDrive,
  Image,
  Key,
  Layers,
  Layout,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Music,
  Network,
  Package,
  Rocket,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Terminal,
  Wifi,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

// APP_ICONS is the curated set of icons selectable for an app. Keys are the
// stored icon names (kebab-ish, matching lucide); values are the components.
export const APP_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "app-window": AppWindow,
  archive: Archive,
  "bar-chart": BarChart,
  bell: Bell,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  "file-text": FileText,
  flame: Flame,
  folder: Folder,
  gamepad: Gamepad2,
  globe: Globe,
  "hard-drive": HardDrive,
  image: Image,
  key: Key,
  layers: Layers,
  layout: Layout,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  monitor: Monitor,
  music: Music,
  network: Network,
  package: Package,
  rocket: Rocket,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  terminal: Terminal,
  wifi: Wifi,
  workflow: Workflow,
  zap: Zap,
};

export const APP_ICON_NAMES = Object.keys(APP_ICONS);

// getAppIcon returns the component for a stored icon name, or undefined.
export function getAppIcon(name?: string): LucideIcon | undefined {
  if (!name) return undefined;
  return APP_ICONS[name];
}
