// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/infra/transport/grpc/proto/hub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -----------------------------------------------------------------------------
// Status / base
// -----------------------------------------------------------------------------
type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNSPECIFIED       ResponseCode = 0
	ResponseCode_RESPONSE_CODE_SUCCESS           ResponseCode = 1
	ResponseCode_RESPONSE_CODE_INVALID_REQUEST   ResponseCode = 2
	ResponseCode_RESPONSE_CODE_TOO_MANY_REQUESTS ResponseCode = 3
	ResponseCode_RESPONSE_CODE_UNAUTHORIZED      ResponseCode = 4
	ResponseCode_RESPONSE_CODE_SERVER_ERROR      ResponseCode = 5
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNSPECIFIED",
		1: "RESPONSE_CODE_SUCCESS",
		2: "RESPONSE_CODE_INVALID_REQUEST",
		3: "RESPONSE_CODE_TOO_MANY_REQUESTS",
		4: "RESPONSE_CODE_UNAUTHORIZED",
		5: "RESPONSE_CODE_SERVER_ERROR",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED":       0,
		"RESPONSE_CODE_SUCCESS":           1,
		"RESPONSE_CODE_INVALID_REQUEST":   2,
		"RESPONSE_CODE_TOO_MANY_REQUESTS": 3,
		"RESPONSE_CODE_UNAUTHORIZED":      4,
		"RESPONSE_CODE_SERVER_ERROR":      5,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_infra_transport_grpc_proto_hub_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_internal_infra_transport_grpc_proto_hub_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{0}
}

type BaseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id for this message (idempotency-friendly)
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Set once identity is known
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// For rolling upgrades (e.g., "1.0.0")
	ProtocolVersion string `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseMessage) Reset() {
	*x = BaseMessage{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMessage) ProtoMessage() {}

func (x *BaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMessage.ProtoReflect.Descriptor instead.
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *BaseMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BaseMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BaseMessage) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type BaseResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ResponseCode    ResponseCode           `protobuf:"varint,3,opt,name=response_code,json=responseCode,proto3,enum=proto.ResponseCode" json:"response_code,omitempty"`
	Detail          string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"` // human-readable
	AgentId         string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *BaseResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BaseResponse) GetResponseCode() ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return ResponseCode_RESPONSE_CODE_UNSPECIFIED
}

func (x *BaseResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *BaseResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BaseResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type App struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{2}
}

func (x *App) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

// -----------------------------------------------------------------------------
// Registration / health
// -----------------------------------------------------------------------------
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseMessage           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {"os":"linux","arch":"amd64"}
	Features      map[string]bool        `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`        // {"can_install":true}
	Apps          []*App                 `protobuf:"bytes,4,rep,name=apps,proto3" json:"apps,omitempty"`                                                                                           // installed apps
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentRequest) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterAgentRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgentRequest) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *RegisterAgentRequest) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseMessage           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{5}
}

func (x *AgentHeartbeat) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

type AgentHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeatResponse) Reset() {
	*x = AgentHeartbeatResponse{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeatResponse) ProtoMessage() {}

func (x *AgentHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*AgentHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{6}
}

func (x *AgentHeartbeatResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// -----------------------------------------------------------------------------
// Generic request/response envelopes
// -----------------------------------------------------------------------------
type RequestEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *BaseMessage           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Correlation id for this request. By convention, set to base.message_id.
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Free-form type, e.g., "install_app", "fetch_logs"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Content negotiation helpers; JSON today, protobuf later if needed.
	ContentType   string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`       // e.g., "application/json"
	SchemaVersion string `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // optional semantic version of payload
	// Command-specific payload (JSON or other by content_type)
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEnvelope) Reset() {
	*x = RequestEnvelope{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvelope) ProtoMessage() {}

func (x *RequestEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvelope.ProtoReflect.Descriptor instead.
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{7}
}

func (x *RequestEnvelope) GetBase() *BaseMessage {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RequestEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequestEnvelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RequestEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RequestEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResponseEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// MUST echo the initiating RequestEnvelope.request_id
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Same semantic "type" as the request (or a subtype like "install_app.result")
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ContentType   string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // e.g., "application/json"
	SchemaVersion string `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Command-specific payload
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEnvelope) Reset() {
	*x = ResponseEnvelope{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnvelope) ProtoMessage() {}

func (x *ResponseEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnvelope.ProtoReflect.Descriptor instead.
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseEnvelope) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ResponseEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseEnvelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ResponseEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ResponseEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// -----------------------------------------------------------------------------
// Bidirectional stream wrappers
// -----------------------------------------------------------------------------
type ServerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ServerCommand_HeartbeatResponse
	//	*ServerCommand_Request
	Command       isServerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{9}
}

func (x *ServerCommand) GetCommand() isServerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServerCommand) GetHeartbeatResponse() *AgentHeartbeatResponse {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_HeartbeatResponse); ok {
			return x.HeartbeatResponse
		}
	}
	return nil
}

func (x *ServerCommand) GetRequest() *RequestEnvelope {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_Request); ok {
			return x.Request
		}
	}
	return nil
}

type isServerCommand_Command interface {
	isServerCommand_Command()
}

type ServerCommand_HeartbeatResponse struct {
	// Responses to agent-initiated messages
	HeartbeatResponse *AgentHeartbeatResponse `protobuf:"bytes,1,opt,name=heartbeat_response,json=heartbeatResponse,proto3,oneof"`
}

type ServerCommand_Request struct {
	// Server-initiated commands (50+)
	Request *RequestEnvelope `protobuf:"bytes,50,opt,name=request,proto3,oneof"`
}

func (*ServerCommand_HeartbeatResponse) isServerCommand_Command() {}

func (*ServerCommand_Request) isServerCommand_Command() {}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Response
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP(), []int{10}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResponse() *ResponseEnvelope {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Heartbeat struct {
	// Agent-initiated messages
	Heartbeat *AgentHeartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Response struct {
	// Responses to server-initiated commands (50+)
	Response *ResponseEnvelope `protobuf:"bytes,50,opt,name=response,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Message() {}

func (*AgentMessage_Response) isAgentMessage_Message() {}

var File_internal_infra_transport_grpc_proto_hub_proto protoreflect.FileDescriptor

const file_internal_infra_transport_grpc_proto_hub_proto_rawDesc = "" +
	"\n" +
	"-internal/infra/transport/grpc/proto/hub.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\vBaseMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\"\xff\x01\n" +
	"\fBaseResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\rresponse_code\x18\x03 \x01(\x0e2\x13.proto.ResponseCodeR\fresponseCode\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\"u\n" +
	"\x03App\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\"\xf6\x02\n" +
	"\x14RegisterAgentRequest\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.proto.BaseMessageR\x04base\x12Q\n" +
	"\fcapabilities\x18\x02 \x03(\v2-.proto.RegisterAgentRequest.CapabilitiesEntryR\fcapabilities\x12E\n" +
	"\bfeatures\x18\x03 \x03(\v2).proto.RegisterAgentRequest.FeaturesEntryR\bfeatures\x12\x1e\n" +
	"\x04apps\x18\x04 \x03(\v2\n" +
	".proto.AppR\x04apps\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"@\n" +
	"\x15RegisterAgentResponse\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.proto.BaseResponseR\x04base\"8\n" +
	"\x0eAgentHeartbeat\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.proto.BaseMessageR\x04base\"A\n" +
	"\x16AgentHeartbeatResponse\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.proto.BaseResponseR\x04base\"\xd0\x01\n" +
	"\x0fRequestEnvelope\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.proto.BaseMessageR\x04base\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\tR\rschemaVersion\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\xd2\x01\n" +
	"\x10ResponseEnvelope\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.proto.BaseResponseR\x04base\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\tR\rschemaVersion\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\x9e\x01\n" +
	"\rServerCommand\x12N\n" +
	"\x12heartbeat_response\x18\x01 \x01(\v2\x1d.proto.AgentHeartbeatResponseH\x00R\x11heartbeatResponse\x122\n" +
	"\arequest\x182 \x01(\v2\x16.proto.RequestEnvelopeH\x00R\arequestB\t\n" +
	"\acommand\"\x87\x01\n" +
	"\fAgentMessage\x125\n" +
	"\theartbeat\x18\x01 \x01(\v2\x15.proto.AgentHeartbeatH\x00R\theartbeat\x125\n" +
	"\bresponse\x182 \x01(\v2\x17.proto.ResponseEnvelopeH\x00R\bresponseB\t\n" +
	"\amessage*\xd0\x01\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESPONSE_CODE_SUCCESS\x10\x01\x12!\n" +
	"\x1dRESPONSE_CODE_INVALID_REQUEST\x10\x02\x12#\n" +
	"\x1fRESPONSE_CODE_TOO_MANY_REQUESTS\x10\x03\x12\x1e\n" +
	"\x1aRESPONSE_CODE_UNAUTHORIZED\x10\x04\x12\x1e\n" +
	"\x1aRESPONSE_CODE_SERVER_ERROR\x10\x052\x9c\x01\n" +
	"\fAgentService\x12L\n" +
	"\rRegisterAgent\x12\x1b.proto.RegisterAgentRequest\x1a\x1c.proto.RegisterAgentResponse\"\x00\x12>\n" +
	"\vAgentStream\x12\x13.proto.AgentMessage\x1a\x14.proto.ServerCommand\"\x00(\x010\x01B*Z(winterflow/internal/transport/grpc/protob\x06proto3"

var (
	file_internal_infra_transport_grpc_proto_hub_proto_rawDescOnce sync.Once
	file_internal_infra_transport_grpc_proto_hub_proto_rawDescData []byte
)

func file_internal_infra_transport_grpc_proto_hub_proto_rawDescGZIP() []byte {
	file_internal_infra_transport_grpc_proto_hub_proto_rawDescOnce.Do(func() {
		file_internal_infra_transport_grpc_proto_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_transport_grpc_proto_hub_proto_rawDesc), len(file_internal_infra_transport_grpc_proto_hub_proto_rawDesc)))
	})
	return file_internal_infra_transport_grpc_proto_hub_proto_rawDescData
}

var file_internal_infra_transport_grpc_proto_hub_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_infra_transport_grpc_proto_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_infra_transport_grpc_proto_hub_proto_goTypes = []any{
	(ResponseCode)(0),              // 0: proto.ResponseCode
	(*BaseMessage)(nil),            // 1: proto.BaseMessage
	(*BaseResponse)(nil),           // 2: proto.BaseResponse
	(*App)(nil),                    // 3: proto.App
	(*RegisterAgentRequest)(nil),   // 4: proto.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),  // 5: proto.RegisterAgentResponse
	(*AgentHeartbeat)(nil),         // 6: proto.AgentHeartbeat
	(*AgentHeartbeatResponse)(nil), // 7: proto.AgentHeartbeatResponse
	(*RequestEnvelope)(nil),        // 8: proto.RequestEnvelope
	(*ResponseEnvelope)(nil),       // 9: proto.ResponseEnvelope
	(*ServerCommand)(nil),          // 10: proto.ServerCommand
	(*AgentMessage)(nil),           // 11: proto.AgentMessage
	nil,                            // 12: proto.RegisterAgentRequest.CapabilitiesEntry
	nil,                            // 13: proto.RegisterAgentRequest.FeaturesEntry
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_internal_infra_transport_grpc_proto_hub_proto_depIdxs = []int32{
	14, // 0: proto.BaseMessage.timestamp:type_name -> google.protobuf.Timestamp
	14, // 1: proto.BaseResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: proto.BaseResponse.response_code:type_name -> proto.ResponseCode
	1,  // 3: proto.RegisterAgentRequest.base:type_name -> proto.BaseMessage
	12, // 4: proto.RegisterAgentRequest.capabilities:type_name -> proto.RegisterAgentRequest.CapabilitiesEntry
	13, // 5: proto.RegisterAgentRequest.features:type_name -> proto.RegisterAgentRequest.FeaturesEntry
	3,  // 6: proto.RegisterAgentRequest.apps:type_name -> proto.App
	2,  // 7: proto.RegisterAgentResponse.base:type_name -> proto.BaseResponse
	1,  // 8: proto.AgentHeartbeat.base:type_name -> proto.BaseMessage
	2,  // 9: proto.AgentHeartbeatResponse.base:type_name -> proto.BaseResponse
	1,  // 10: proto.RequestEnvelope.base:type_name -> proto.BaseMessage
	2,  // 11: proto.ResponseEnvelope.base:type_name -> proto.BaseResponse
	7,  // 12: proto.ServerCommand.heartbeat_response:type_name -> proto.AgentHeartbeatResponse
	8,  // 13: proto.ServerCommand.request:type_name -> proto.RequestEnvelope
	6,  // 14: proto.AgentMessage.heartbeat:type_name -> proto.AgentHeartbeat
	9,  // 15: proto.AgentMessage.response:type_name -> proto.ResponseEnvelope
	4,  // 16: proto.AgentService.RegisterAgent:input_type -> proto.RegisterAgentRequest
	11, // 17: proto.AgentService.AgentStream:input_type -> proto.AgentMessage
	5,  // 18: proto.AgentService.RegisterAgent:output_type -> proto.RegisterAgentResponse
	10, // 19: proto.AgentService.AgentStream:output_type -> proto.ServerCommand
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_infra_transport_grpc_proto_hub_proto_init() }
func file_internal_infra_transport_grpc_proto_hub_proto_init() {
	if File_internal_infra_transport_grpc_proto_hub_proto != nil {
		return
	}
	file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[9].OneofWrappers = []any{
		(*ServerCommand_HeartbeatResponse)(nil),
		(*ServerCommand_Request)(nil),
	}
	file_internal_infra_transport_grpc_proto_hub_proto_msgTypes[10].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_transport_grpc_proto_hub_proto_rawDesc), len(file_internal_infra_transport_grpc_proto_hub_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_transport_grpc_proto_hub_proto_goTypes,
		DependencyIndexes: file_internal_infra_transport_grpc_proto_hub_proto_depIdxs,
		EnumInfos:         file_internal_infra_transport_grpc_proto_hub_proto_enumTypes,
		MessageInfos:      file_internal_infra_transport_grpc_proto_hub_proto_msgTypes,
	}.Build()
	File_internal_infra_transport_grpc_proto_hub_proto = out.File
	file_internal_infra_transport_grpc_proto_hub_proto_goTypes = nil
	file_internal_infra_transport_grpc_proto_hub_proto_depIdxs = nil
}
