package dockercompose

import (
	"os"
	"path/filepath"
)

// runRel is the manual-run helper script: derived state regenerated on every
// deploy (gitignored), mirroring winterflow's exact docker compose invocation
// so a manual run controls the same stack.
const runRel = ".winterflow/run.sh"

// managedEnvVar is reserved: the project name only ever travels as the
// --project-name flag (winterflow's invocations and run.sh), never through the
// committed .env, which belongs to the user and is often loaded into
// containers via `env_file: .env`. User variables with this name are dropped
// at save; apps saved by older agents still carry it in .env, so GetApp hides
// it until their next save rewrites the file.
const managedEnvVar = "COMPOSE_PROJECT_NAME"

// runHelperScript renders the helper for a project. composeFile is "" when
// compose auto-detects the winterflow-authored root compose file.
func runHelperScript(project, composeFile string) []byte {
	prefix := "exec docker compose --project-name " + project
	if composeFile != "" {
		prefix += ` -f "` + composeFile + `"`
	}
	return []byte(`#!/bin/sh
# Generated by winterflow on every deploy — do not edit.
# Runs docker compose with the same flags winterflow uses, so a manual run
# controls the same stack. Usage: .winterflow/run.sh up -d | down | logs -f
cd "$(dirname "$0")/.." || exit 1
if [ -f .env.secrets ]; then
	` + prefix + ` --env-file .env --env-file .env.secrets "$@"
fi
` + prefix + ` --env-file .env "$@"
`)
}

// writeRunHelper (re)writes the app's manual-run helper.
func (r *Repository) writeRunHelper(appID string) error {
	dir := r.appDataDir(appID)
	script := runHelperScript(projectName(appID), r.composeFile(dir, r.appSourceSpec(dir)))
	path := filepath.Join(dir, runRel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, script, 0o755); err != nil {
		return err
	}
	// WriteFile's perm only applies on create; keep regenerated files executable.
	return os.Chmod(path, 0o755)
}
